server:
  port: 3400

database:
  auth:
    url: 'mongodb://localhost:27017/auth'
    id: 'test'
    pw: 'test1234'
    auth_source: 'admin'

  event:
    url: 'mongodb://localhost:27017/event'
    id: 'test'
    pw: 'test1234'
    auth_source: 'admin'