server:
  port: 3200

database:
  auth:
    url: 'mongodb://localhost:3500/auth'
    id: 'test'
    pw: 'test1234'
    auth_source: 'admin'

security:
  jwt:
    private: 'private.pem'
    public: 'public.pem'
    access_expire: 1
    refresh_expire: 10
    issuer: 'http://localhost'
    audience: 'http://localhost'